root_train_image_path: "../dataset/pngs/balanced_images/train"
root_train_label_path: "../dataset/annotations/train.json"
root_test_image_path: "../dataset/pngs/balanced_images/test"
root_test_label_path: "../dataset/annotations/test.json"

image_height: 512
image_width: 512

batch_size: 8
loss_function: "MixedLoss"
optimizer: "Adam"
learning_rate: 0.0001
scheduler: 'ReduceLROnPlateau'
step_size: 30
gamma: 0.1

num_epochs: 48
device: 'cuda'
save_path: "./checkpoints"
continue_training: False
continue_training_path: "/home/dhgbao/VinBrain/Pneumothorax_Segmentation/code/checkpoints/model-ckpt-best.pt"