root_df_path: "/home/dhgbao/VinBrain/Pneumothorax_Segmentation/dataset/dicom/stage2_preprocessing_data.csv"
root_test_path: "/home/dhgbao/VinBrain/Pneumothorax_Segmentation/dataset/dicom/stage_2_test"
positive_only: False

image_height: 512
image_width: 512

batch_size: 16
loss_function: "ComboLoss"
optimizer: "Adam"
learning_rate: 0.0001
scheduler: 'ReduceLROnPlateau'
step_size: 30
gamma: 0.1
backbone: "efficientnet-b4"

annotation_type: dataframe
transform: True
num_epochs: 200
device: 'cuda'
save_path: "./checkpoints"
continue_training: False
save_checkpoint: "/home/dhgbao/VinBrain/Pneumothorax_Segmentation/vinbrain_internship/checkpoints/nguyen_df.pt"