root_df_path: "/home/dhgbao/VinBrain/Pneumothorax_Segmentation/dataset/dicom/positive_stage2_preprocessing_data.csv"
root_test_path: "/home/dhgbao/VinBrain/Pneumothorax_Segmentation/dataset/dicom/stage_2_test"
positive_only: True

image_height: 512
image_width: 512

batch_size: 8
loss_function: "MixedLoss"
optimizer: "Nadam"
learning_rate: 0.0001
scheduler: 'CosineAnnealingLR'
step_size: 30
gamma: 0.1
backbone: "se_resnext50_32x4d"

annotation_type: dataframe
transform: True
num_epochs: 100
device: 'cuda'
save_path: "./checkpoints"
continue_training: False
save_checkpoint: "/home/dhgbao/VinBrain/Pneumothorax_Segmentation/vinbrain_internship/checkpoints/positive.pt"