root_df_path: "/home/dhgbao/VinBrain/assignments/others_code/nguyen/siimacr/nguyen_preprocessing_data.csv"
root_test_path: "/home/dhgbao/VinBrain/assignments/dataset/siim/nguyen_dicom/siim-acr-pneumothorax-segmentation/stage_2_images"
positive_only: False

image_height: 256
image_width: 256

batch_size: 8
loss_function: "MixedLoss"
optimizer: "Nadam"
learning_rate: 0.0001
scheduler: 'CosineAnnealingLR'
T_max: 10
step_size: 30
gamma: 0.1
backbone: "torchvision.resnext101"
weights: {'bce':3, 'dice':1, 'focal':5}

annotation_type: dataframe
transform: False
num_epochs: 50
device: 'cuda'
save_path: "./checkpoints"
continue_training: True
trained_weights: "/home/dhgbao/VinBrain/assignments/others_code/nguyen/siimacr/model_v4_1.pth"
save_checkpoint: "/home/dhgbao/VinBrain/assignments/vinbrain_internship/SIIM/checkpoints/resnext_torchvision_nguyen_ckpt.pt"