root_train_image_path: "/home/dhgbao/VinBrain/assignments/dataset/NeoPolyp/split/train"
root_train_label_path: "/home/dhgbao/VinBrain/assignments/dataset/NeoPolyp/split/train_mask"
root_valid_image_path: "/home/dhgbao/VinBrain/assignments/dataset/NeoPolyp/split/valid"
root_valid_label_path: "/home/dhgbao/VinBrain/assignments/dataset/NeoPolyp/split/valid_mask"
root_test_image_path: "/home/dhgbao/VinBrain/assignments/dataset/NeoPolyp/split/test"

image_height: 480
image_width: 640

batch_size: 4
loss_function: "CrossEntropyLoss"
optimizer: "Nadam"
learning_rate: 0.0001
scheduler: 'CosineAnnealingWarmRestarts'
T_mult: 2
backbone: "deeplabv3_resnet101"
classes: ['background', 'neoplastic', 'non-neoplastic']
encoder_weights: 'imagenet'
activation: 

transform: True
num_epochs: 50
device: 'cuda'
continue_training: False
trained_weights: "/home/dhgbao/VinBrain/assignments/vinbrain_internship/NeoPolyp/checkpoints/deeplabv3_resnet101.pt"
save_checkpoint: "/home/dhgbao/VinBrain/assignments/vinbrain_internship/NeoPolyp/checkpoints/deeplabv3_resnet101.pt"
csv_name: "deeplabv3_resnet101"