root_train_image_path: "/home/dhgbao/VinBrain/assignments/dataset/NeoPolyp/split/train"
root_train_label_path: "/home/dhgbao/VinBrain/assignments/dataset/NeoPolyp/split/train_mask"
root_valid_image_path: "/home/dhgbao/VinBrain/assignments/dataset/NeoPolyp/split/valid"
root_valid_label_path: "/home/dhgbao/VinBrain/assignments/dataset/NeoPolyp/split/valid_mask"
positive_only: False

image_height: 512
image_width: 512

batch_size: 16
loss_function: "CrossEntropyLoss"
optimizer: "Nadam"
learning_rate: 0.0001
scheduler: 'ReduceLROnPlateau'
T_max: 10
step_size: 30
gamma: 0.1
backbone: "resnet34"
classes: ['background', 'neoplastic', 'non-neoplastic']
encoder_weights: 'imagenet'
activation: 'sigmoid'

transform: False
num_epochs: 50
device: 'cuda'
continue_training: False
trained_weights: "/home/dhgbao/VinBrain/assignments/vinbrain_internship/NeoPolyp/checkpoints/best.pt"
save_checkpoint: "/home/dhgbao/VinBrain/assignments/vinbrain_internship/NeoPolyp/checkpoints/best.pt"