root_train_image_path: "/home/dhgbao/VinBrain/assignments/dataset/NeoPolyp/split/train_aug_400"
root_train_label_path: "/home/dhgbao/VinBrain/assignments/dataset/NeoPolyp/split/train_aug_mask_400"
root_valid_image_path: "/home/dhgbao/VinBrain/assignments/dataset/NeoPolyp/split/valid"
root_valid_label_path: "/home/dhgbao/VinBrain/assignments/dataset/NeoPolyp/split/valid_mask"
root_test_image_path: "/home/dhgbao/VinBrain/assignments/dataset/NeoPolyp/split/test"
positive_only: False

image_height: 960
image_width: 960

batch_size: 10
loss_function: "smpFocalLoss"
optimizer: "Nadam"
learning_rate: 0.0001
scheduler: 'CosineAnnealingWarmRestarts'
T_mult: 2
backbone: "sanet"
classes: ['background', 'neoplastic', 'non-neoplastic']
probability_correction_strategy: False
refine_masks: True

transform: True
num_epochs: 50
device: 'cuda'
continue_training: False
trained_weights: "/home/dhgbao/VinBrain/assignments/vinbrain_internship/NeoPolyp/checkpoints/sanet_aug_focal.pt"
save_checkpoint: "/home/dhgbao/VinBrain/assignments/vinbrain_internship/NeoPolyp/checkpoints/sanet_aug_focal.pt"
csv_name: "sanet_aug_focal"