root_train_image_path: "/home/dhgbao/VinBrain/Pneumothorax_Segmentation/dataset/chest-xray/split/train"
root_train_label_path: "/home/dhgbao/VinBrain/Pneumothorax_Segmentation/dataset/chest-xray/split/train_mask"
root_test_image_path: "/home/dhgbao/VinBrain/Pneumothorax_Segmentation/dataset/chest-xray/split/test"
root_test_label_path: "/home/dhgbao/VinBrain/Pneumothorax_Segmentation/dataset/chest-xray/split/test_mask"
positive_only: False


image_height: 256
image_width: 256

batch_size: 24
loss_function: "MixedLoss"
weights: {'bce':3, 'dice':1, 'focal':5}
optimizer: "Nadam"
learning_rate: 0.0001
scheduler: 'CosineAnnealingLR'
T_max: 10
step_size: 30
gamma: 0.1
backbone: "torchvision.resnext101"

annotation_type: images
transform: True
num_epochs: 50
device: 'cuda'
continue_training: False
save_checkpoint: "/home/dhgbao/VinBrain/Pneumothorax_Segmentation/vinbrain_internship/checkpoints/chest_resnext.pt"