root_train_image_path: "/home/dhgbao/VinBrain/Pneumothorax_Segmentation/dataset/nguyen/split/train"
root_train_label_path: "/home/dhgbao/VinBrain/Pneumothorax_Segmentation/dataset/nguyen/split/train_mask"
root_test_image_path: "/home/dhgbao/VinBrain/Pneumothorax_Segmentation/dataset/nguyen/split/test"
root_test_label_path: "/home/dhgbao/VinBrain/Pneumothorax_Segmentation/dataset/nguyen/split/test_mask"
positive_only: False

image_height: 256
image_width: 256

batch_size: 16
loss_function: "DiceLoss"
optimizer: "Adam"
learning_rate: 0.0001
scheduler: 'ReduceLROnPlateau'
step_size: 30
gamma: 0.1
backbone: "efficientnet-b4"

annotation_type: images
transform: True
num_epochs: 200
device: 'cuda'
save_path: "./checkpoints"
continue_training: True
save_checkpoint: "/home/dhgbao/VinBrain/Pneumothorax_Segmentation/vinbrain_internship/checkpoints/nguyen.pt"